### PR TITLE
cli improvements & fixes

### PR DESCRIPTION
**Pull request by nrdxp**
Tired of the hacky methods of deploying and running commands, I decided to go ahead and clean up the cli a bit and allow for targeting specific node classes for `ssh`, and `deploy` commands

Also, since it's super annoying for `bitte deploy` to take a super long time without any feedback, I also fixed the stdout of the nix build commands so we can again see build progress during a deployment.

Some other niceties for `deploy`: since we almost always disable rollbacks I went ahead and inverted the flags, so now you have to pass the rollback settings if you want them otherwise they are disbled by default, also, instead of exiting on error, simply log the error and continue so we don't have to reinvoke if one of the clients failed to activate (since this is sometimes a false positive anyway).

Before merging, I'd probably also like to add a `bitte scp` command, which should be mostly just refactoring the existing ssh code path, so not too much work :crossed_fingers:

### CODE REVIEW

**Review by dermetfan — CHANGES_REQUESTED** [review]
```
❯ nix build .#x86_64-linux.cli.packages.bitte
error: hash mismatch in fixed-output derivation '/nix/store/518vixh76w317bdzzrx2wlxarrhi7gi0-deploy-rs-b086e4d.drv':
         specified: sha256-/CTQuJzFK8pO2d4S5uKhHwT+QiNfnbCKSx7O2tW0GXQ=
            got:    sha256-X4eSLR1McUik0vDYWDCqIaWY1WjhIg4PIWXQ32WDFxg=
error: 1 dependencies of derivation '/nix/store/14r4w3qzn1xq7zy6psxvkhm70hpzpj53-deploy-rs-0.1.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/42cl4fr6ivx1narhkwx1j69fjkrd21by-cargo-vendor-dir.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1frh8wvvz62xigzyfrzai8yb6rw93hxq-bitte.drv' failed to build
```

**Comment by nrdxp** [comment]
fixed

**Review by johnalotoski — APPROVED** [review]

**Review by dermetfan — APPROVED** [review]
The description of these flags should probably be inverted:

> $ bitte deploy --help
> --auto-rollback     Do **not** attempt rollback if activation fails
> --magic-rollback   Do **not** do a magic rollback (see documentation)

That's all I could find though

**Comment by nrdxp** [comment]
fixed, also I changed the semantic of `--skip-check` to `--do-check` since the checks often fail.

**Pull request merged**
