### PR TITLE
docker-distribution 2.7.1 -> 2.8.1

### PR DESCRIPTION
**Pull request by manveru**

### CODE REVIEW

**Comment by kreisys** [comment]
1. what did they add to unstable that we need?
2. wouldn't it be sufficient to just override the `src` and `version` of the original nixpkgs drv instead of vendoring in the whole thing?

**Comment by manveru** [comment]
I mostly was debugging some issues with the registry today, and found that the latest version is 2.8.1 and includes a couple of bug- and security fixes.
I guess the override might work, but i found it easier to just copy&paste the original ^^;

**Review by kreisys — APPROVED** [review]
Nothing objectionable. :shipit:

**Review by blaggacao — APPROVED** [review]
LGTM, no CIAL.

**Review by johnalotoski — APPROVED** [review]

**Pull request merged**
