### PR TITLE
fix all the bootstrapping

### PR DESCRIPTION
**Pull request by blaggacao**
... and some more.

- cleanup(secrets): #0 remove old & unused (manual) secrets code
- cleanup(s3-download): #0 remove s3-download
- fix(secrets): #0 don't attest a random public ip
- imp(ami): #0 enable efi boot on ami images for kexec
- imp(provision): #0 kexec if diff in kernel version during provision
- bump(nixos): #0 only later versions have the ami backports we need
- rem old zfsAmi
- imp(ami): #0 add ami upload convenience script
- fix(flock): #0 the previous version did not lock reliably
- revert(ami): #0 switch off efi boot (needs furthe debugging)
- fix(provisioning): #0 use kexec only if available othewise use reboot
- fix(bootstrap): #0 start consul in acl mode and use master token until
- imp(qol): #0 avoid accidentially screwing domain cert procuration
- fix(oauth): #0 oauth _wants_ secrets-oauth
- imp(ami): #0 venture into efi-amis again
- imp(tf): #0 allow passing args to the underlying commands
- revert(amis): #0 the efi-amis fail
- imp(amis): #0 add serial console debugging to amis
- fix(amis): #0 use tested upstream init logic
- clean up systemPackages a bit
- fix(zfs): #0 the custom runtime is not upstream-compatible
- imp(ami) core & client ami ids (with slim profile)
- fix(ami): cleanup the code path & make sure that asg groups are
- fix(core): #0 dedup core / slim / rm boot
- Crowning of the refactoring: onable client ami upload again
- fixup
- refact(iam): #0 kick off the cluster-hydrate conceptualization
- fixup: core CSR
- fix(bootstrap): #0 sign vault pki intermediate as part of hydration
- fix(bootstrap): #0 align root cert w/ core cert detection
- fix(user-data): #0 introduced wrong quotes during refactoring
- fixup: vault intermediate cert format
- refact(tf): #0 distribute network workspace into core / clients
- cleanup(depr): #0 polish up deprecated stuff in-tree
- cleanup(lib): #0 mkBitteStack & deps, use terranix flake
- cleanup(flake): #0 rm sipleFlake, hydra-provisioner & nixpkgs-fmt
- imp(bitte-stack): #0 add mkDeploy to bitte stack
- fix(i/o): #0 use non-naersk treefmt version & expose bitte.lib again
- imp(fmt): #0 add treefmt config
- treefmt
- imp(shell): #0 anticipate typical treefmt deps
- fix(depr): #0 fix more internal uses of deprecated stuff
- ...

### CODE REVIEW

**Comment by jonringer** [comment]
O.o

got some conficts.

How are we supposed to test all this? lol

**Comment by nrdxp** [comment]
well with the portal cluster gone down, I have occassion to try this out now:
It seems like you've made some fairly big changes here though so it might be good to either update the logseq with new instructions or include an md doc in tree

**Comment by blaggacao** [comment]
> How are we supposed to test all this? lol

Fortunately, two clusters already run on this with less issues than before this branch. :smile:

**Comment by nrdxp** [comment]
Indeed, thankfully @jonringer, this helped me out tremendously yesterday to get the kevm cluster rebootstrapped. It was as simple as a terraform core plan/apply cycle and all the core services were properly bootstrapped. If you wanna test yourself I think David started a test cluster somewhere you could play with irrc.

**Pull request merged**
