### PR TITLE
bitteShell: make the prompt more prompty

### PR DESCRIPTION
**Pull request by craigem**

### CODE REVIEW

**Review by manveru — APPROVED** [review]
LGTM, i never see the bash one anyway :)

**Comment by craigem** [comment]
> LGTM, i never see the bash one anyway :)

Are you dropping into another shell like zsh or fish?

**Comment by kreisys** [comment]
> LGTM, i never see the bash one anyway :)

I found that option documented next to the `extra-*` options that I didn't know about so I added it for shits and giggles but now that I'm thinking about it I have also never seen it. We both use starship.rs so maybe that's why... But hey, happy someone's enjoying it 😌

**Review by kreisys — APPROVED** [review]
:shipit:

**Pull request merged**
